title: Troop 51 Documentation
theme: just-the-docs

# Where your generated docs live
collections:
  docs:
    output: true
    permalink: /:path/

just_the_docs:
  collections:
    docs:
      name: Documentation

# Set the docs folder
defaults:
  - scope:
      path: "output_docs"
    values:
      layout: default
      collection: docs
